---
title: "Izvješće"
subtitle: "Prilagodba modela podatcima i linearna regresija"
author: "Matija Bačić, Marko Lazarić, Roman Yatsukha"
date: "12.05.2019."
output: pdf_document
---
  
```{r, echo = FALSE}
library(knitr)
opts_chunk$set(tidy.opts=list(width.cutoff=60),tidy=TRUE)
```

```{r}
dice <- read.delim("dice.dat", header=FALSE)

# 3.
# Granice postavljamo sami tako da se pomaknemo za 0.5 na lijevo od najmanjeg podatka
# iz uzorka i za 0.5 na desno od najveceg podatka iz uzorka te zatim podijelimo taj
# interval na 10 ekvidistantnih intervala (pomocu 11 tocaka)

barplot(dice$V2, names.arg = dice$V1)
barplot(dice$V3, names.arg = dice$V1)

# Procjena p parametra binomne distribucije koristeći maksimalnu izglednost
# p' = x / n, odnosno broj povoljnih ishoda kroz broj svih ishoda
# u ovom slucaju broj 5/6 kroz ukupan broj ishoda

desirable.outcomes <- function(values, categories)
  sum(categories * values)

all.outcomes <- function(values, categories)
  max(categories) * sum(values)

estimate.p <- function(values, categories)
  desirable.outcomes(values, categories) / all.outcomes(values, categories)

p.0 = estimate.p(dice$V2, dice$V1)
p.1 = estimate.p(dice$V3, dice$V1)

sprintf(fmt = 'Procjena parametra p za I. uzorak: %.4f',  p.0)
sprintf(fmt = 'Procjena parametra p za II. uzorak: %.4f', p.1)

confidence.interval <- function(values, categories, interval) {
  alpha.half <- (1 - interval) / 2
  
  x <- desirable.outcomes(values, categories)
  n <- all.outcomes(values, categories)
  
  c(qbeta(alpha.half, x, n - x + 1), qbeta(1 - alpha.half, x + 1, n - x))
}

interval = 0.95

cp.0 = confidence.interval(dice$V2, dice$V1, interval)
cp.1 = confidence.interval(dice$V3, dice$V1, interval)

sprintf(fmt = '%d%% postotni interval pouzdanosti za I. uzorak: [%.4f, %.4f]',  interval * 100, cp.0[1], cp.0[2])
sprintf(fmt = '%d%% postotni interval pouzdanosti za II. uzorak: [%.4f, %.4f]', interval * 100, cp.1[1], cp.1[2])

```

```{r}
library(ggplot2)
forbes <- read.table("forbes.dat", quote="\"", comment.char="")
hooker <- read.table("hooker.dat", quote="\"", comment.char="")
fh_concat <- rbind(forbes, hooker)

names(fh_concat)[names(fh_concat) == "V1"] <- "Vreliste"
names(fh_concat)[names(fh_concat) == "V2"] <- "Tlak"

plot(fh_concat$Vreliste, fh_concat$Tlak)

# LINEARNI MODEL

linear_model <- lm(Vreliste ~ Tlak, data = fh_concat)
linear_model

plot(fh_concat$Tlak, fh_concat$Vreliste, pch=16, xlab = "Tlak", ylab = "Vreliste", cex.lab = 1.3, col = "red" ) + abline(linear_model, col = "blue")

# Ili ggplot:

ggplot(fh_concat, aes(Tlak, Vreliste)) +
  geom_point() +
  stat_smooth(method = lm, size = 1, se = FALSE)

# KVADRATICNI MODEL

Tlak2 <- fh_concat$Tlak^2
quadratic_model <-lm(Vreliste ~ Tlak + Tlak2, data = fh_concat)
quadratic_model

timevalues <- seq(0, 30, 0.1)
predictedcounts <- predict(quadratic_model,list(Tlak=timevalues, Tlak2=timevalues^2))

plot(fh_concat$Tlak, fh_concat$Vreliste, pch=16, xlab = "Tlak", ylab = "Vreliste", cex.lab = 1.3, col = "blue") + lines(timevalues, predictedcounts, col = "darkgreen", lwd = 3)

# Ili ggplot:
ggplot(fh_concat, aes(x = Tlak, y = Vreliste)) +
  geom_point() +
  stat_smooth(method = "lm", formula = y ~ x + I(x^2), size = 1, se = FALSE)

# REZIDUALI
fh_concat$predictedLinear = predict(linear_model)
fh_concat$residualsLinear = residuals(linear_model)
fh_concat$stdResidualsLinear = rstandard(linear_model)
fh_concat$predictedQuadratic = predict(quadratic_model)
fh_concat$residualsQuadratic = residuals(quadratic_model)
fh_concat$stdResidualsQuadratic = rstandard(quadratic_model)

# Linear residuals
ggplot(fh_concat, aes(x = Tlak, y = Vreliste)) +
  geom_smooth(method = "lm", se = FALSE, color = "lightgrey") +     # regression line  
  geom_segment(aes(xend = Tlak, yend = predictedLinear), alpha = .2) +      # draw line from point to line
  geom_point(aes(color = abs(residualsLinear), size = abs(residualsLinear))) +  # size of the points
  scale_color_continuous(low = "green", high = "red") +             # colour of the points mapped to residual size - green smaller, red larger
  guides(color = FALSE, size = FALSE) +                             # Size legend removed
  geom_point(aes(y = predictedLinear), shape = 1) +
  theme_bw()

# Std linear residuals
ggplot(fh_concat, aes(x = Tlak, y = Vreliste)) +
  geom_smooth(method = "lm", se = FALSE, color = "lightgrey") +     # regression line  
  geom_segment(aes(xend = Tlak, yend = predictedLinear), alpha = .2) +      # draw line from point to line
  geom_point(aes(color = abs(stdResidualsLinear), size = abs(stdResidualsLinear))) +  # size of the points
  scale_color_continuous(low = "green", high = "red") +             # colour of the points mapped to residual size - green smaller, red larger
  guides(color = FALSE, size = FALSE) +                             # Size legend removed
  geom_point(aes(y = predictedLinear), shape = 1) +
  theme_bw()

# Quadratic residuals
ggplot(fh_concat, aes(x = Tlak, y = Vreliste)) +
  geom_smooth(method = "lm", se = FALSE, color = "lightgrey") +     # regression line  
  geom_segment(aes(xend = Tlak, yend = predictedQuadratic), alpha = .2) +      # draw line from point to line
  geom_point(aes(color = abs(residualsQuadratic), size = abs(residualsQuadratic))) +  # size of the points
  scale_color_continuous(low = "green", high = "red") +             # colour of the points mapped to residual size - green smaller, red larger
  guides(color = FALSE, size = FALSE) +                             # Size legend removed
  geom_point(aes(y = predictedQuadratic), shape = 1) +
  theme_bw()

# Std linear residuals
ggplot(fh_concat, aes(x = Tlak, y = Vreliste)) +
  geom_smooth(method = "lm", se = FALSE, color = "lightgrey") +     # regression line  
  geom_segment(aes(xend = Tlak, yend = predictedQuadratic), alpha = .2) +      # draw line from point to line
  geom_point(aes(color = abs(stdResidualsQuadratic), size = abs(stdResidualsQuadratic))) +  # size of the points
  scale_color_continuous(low = "green", high = "red") +             # colour of the points mapped to residual size - green smaller, red larger
  guides(color = FALSE, size = FALSE) +                             # Size legend removed
  geom_point(aes(y = predictedQuadratic), shape = 1) +
  theme_bw()

```